#!/bin/bash
# this script to generate alert when disk space exceeds 90%
# grep -v tmpfs to remove tmpfs from the output
a=`df -h | grep -v tmpfs | tail -n+2 | awk '{print $5}' | cut -d % -f1`
for i in $a
do
if [ $i -ge 60 ]
then echo check diskspace $i `df -h | grep $i | tail -n+2`
fi 
done
