#!/bin/bash
rm /backup.tar.gz
tar -cvf /backup.tar /etc
gzip /backup.tar
find /backup.tar.gz -mtime -1 -type f -print &> /dev/null
if [ $? -eq 0  ]
then echo "backup was created"
echo
echo archiving backup
sshpass -p "Password5**" scp /backup.tar.gz moataz@192.168.14.128: /tmp
else echo backup failed
fi
