#!/bin/bash
#this script to record live errors first by first
tail -fn0 /var/log/syslog | while read line
do
echo $line | egrep -i "refused | failed | lost | error | shutdown | offline | interface | rout | network" 
if [ $? -eq 0 ]
then echo $line >> /tmp/failed-messages
fi
done 
